services:

  mcp-pizzerias-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9096:6060
    environment:
      - MCP_HTTP_PORT=6060
    volumes:
      - ./data:/app/data



