# docker compose up --build --no-log-prefix
services:

  mcp-gateway:
    image: docker/mcp-gateway:v2
    ports:
      - 9011:9011
    #use_api_socket: true
    command:
      - --port=9011
      - --transport=streaming
      - --verbose
      - --catalog=/mcp/catalog.yaml
      #- --servers=mcp-files
      - --servers=mcp-snippets,mcp-files
    configs:
      - source: catalog.yaml
        target:
          /mcp/catalog.yaml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/config
    depends_on:
      mcp-snippets:
        condition: service_healthy
      mcp-files:
        condition: service_healthy

  mcp-snippets:
    image: k33g/mcp-snippets-server:0.0.5
    environment:
      MCP_HTTP_PORT: 6060
      LIMIT: 0.6
      MAX_RESULTS: 3
      JSON_STORE_FILE_PATH: store/rag-memory-store.json
      DELIMITER: ----------
    
    volumes:
      - ./snippets:/app/snippets
      - ./store/snippets:/app/store
    models:
      mxbai-embed:
        endpoint_var: MODEL_RUNNER_BASE_URL
        model_var: EMBEDDING_MODEL

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:6060/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


  mcp-files:
    image: k33g/mcp-files-server:0.0.3
    environment:
      MCP_HTTP_PORT: 6060
      LOCAL_WORKSPACE_FOLDER: /app/workspace
    volumes:
      - ./workspace:/app/workspace
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:6060/health"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 40s

  # docker compose attach my-agent
  my-agent:
    image: docker/cagent:1.5.0
    volumes:
      - ./bob.yaml:/app/bob.yaml
    command: ["run", "/app/bob.yaml"]
    tty: true
    stdin_open: true    
    models:
      - agent-model
        
    depends_on:
      mcp-gateway:
        condition: service_started
        
models:

  mxbai-embed:
    model: ai/mxbai-embed-large
  agent-model:
    model: hf.co/menlo/jan-nano-gguf:q4_k_m 

configs:
  catalog.yaml:
    content: |
      registry:
        mcp-snippets:
          remote:
            url: "http://mcp-snippets:6060/mcp"
            transport_type: http

        mcp-files:
          remote:
            url: "http://mcp-files:6060/mcp"
            transport_type: http
