services:

  mcp-crazy-hawaiian-pizzas-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-crazy-hawaiian-pizzas-server
    ports:
      - 9097:6060
    environment:
      - MCP_HTTP_PORT=6060
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9091/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge

